export const ADD_DEVICE = 'ADD_DEVICE';
export const AUTH_LOAD_DEVICE = 'AUTH_LOAD_DEVICE';
export const AUTH_LOAD_DEVICE_SUCCESS = 'AUTH_LOAD_DEVICE_SUCCESS';
export const AUTH_LOAD_DEVICE_FAIL = 'AUTH_LOAD_DEVICE_FAIL';

export const AUTH_DEVICE_SIGNIN = 'AUTH_DEVICE_SIGNIN';
export const AUTH_DEVICE_SIGNIN_SUCCESS = 'AUTH_DEVICE_SIGNIN_SUCCESS';
export const AUTH_DEVICE_SIGNIN_FAIL = 'AUTH_DEVICE_SIGNIN_FAIL';

export const AUTH_DEVICE_SIGNOUT = 'AUTH_DEVICE_SIGNOUT';
export const AUTH_DEVICE_SIGNOUT_SUCCESS = 'AUTH_DEVICE_SIGNOUT_SUCCESS';
export const AUTH_DEVICE_SIGNOUT_FAIL = 'AUTH_DEVICE_SIGNOUT_FAIL';

export const AUTH_DEVICE_SIGNUP = 'AUTH_DEVICE_SIGNUP';
export const AUTH_DEVICE_SIGNUP_SUCCESS = 'AUTH_DEVICE_SIGNUP_SUCCESS';
export const AUTH_DEVICE_SIGNUP_FAIL = 'AUTH_DEVICE_SIGNUP_FAIL';


export const ADD_COMMAND = 'ADD_COMMAND';
export const RECEIVE_COMMAND = 'RECEIVE_COMMAND';

export const ADD_USER = 'ADD_USER';
export const AUTH_USER_SIGNUP = 'AUTH_USER_SIGNUP';
export const AUTH_USER_SIGNOUT = 'AUTH_USER_SIGNOUT';

export const SAVE_USERNAME = 'SAVE_USERNAME';
export const LOAD_USERVALIDATION = 'LOAD_USERVALIDATION';
export const START_USERNAME_VALIDATION = 'START_USERNAME_VALIDATION';

export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const RECEIVE_SOCKET = 'RECEIVE_SOCKET';

export const COMMAND_WORK_SUCCESS = 'COMMAND_WORK_SUCCESS';
export const COMMAND_WORK_FAIL = 'COMMAND_WORK_FAIL';

export const AUTH_USER_SIGNOUT_SUCCESS = 'AUTH_USER_SIGNOUT_SUCCESS';
export const AUTH_USER_SIGNOUT_FAIL = 'AUTH_USER_SIGNOUT_FAIL';

export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const USERNAME_VALIDATION_SUCCESS = 'USERNAME_VALIDATION_SUCCESS';
export const USERNAME_VALIDATION_FAIL = 'USERNAME_VALIDATION_FAIL';

export const LOAD_USERVALIDATION_SUCCESS = 'LOAD_USERVALIDATION_SUCCESS';
export const LOAD_USERVALIDATION_FAIL = 'LOAD_USERVALIDATION_FAIL';